### PR TITLE
Agaton

### PR DESCRIPTION
**Pull request by agtaon**
These are the functions I have used to generate my results together with three notebooks (the same ones as in the paper) showing how to use the functions for different cases.

### CODE REVIEW

**Comment by BenjaminMidtvedt** [comment]
The linter has a few complaints (you can check by pressing Show all checks, details and lint with flake8). VSCode can autoformat it for you. Just go into settings and do auto-format using black (might need to install it via pip). Also enable linting using flake8 to check for linting errors locally Or you can correct it one by one of course. Doesn't have to pass everything if you feel like the formatting guidelines are not correct.

**Comment by BenjaminMidtvedt** [comment]
Also, adding some tests that just makes sure that the functions can be run without crashing would be nice to make sure that future releases don't break anything. Just run the functions and make sure it doesn't crash for example,

**Comment by agtaon** [comment]
Hej! Jag fick ett klagomål om "missing whitespace after ',' ", men VSCode
autoformaterar bort mellanslagen efter kommatecken i funktioner som har
argument på flera rader, tex:

def moving_ellipsoid_plankton(
    im_size_height,
    im_size_width,
    radius=(1.5e-7, 9e-7, 1.5e-7),
    label=0,
    diffusion_constant_coeff=1,
):
Gör det något?

Och tester, kan det vara tex en notebook där alla funktioner körs på rad?
Eller är det snarare en funktion som kör alla funktioner? Typ
def testing_function():
    func1()
    func2()
    func3()
    ...
På något sätt?

Den tis 22 juni 2021 kl 18:16 skrev BenjaminMidtvedt <
***@***.***>:

**Comment by BenjaminMidtvedt** [comment]
Do you use black for formatting? It's in preferences. It's not a big deal if that's the only error.

Preferably a testing function. Check deeptrack/test for how we do it. It's for continuous testing purposes

**Comment by BenjaminMidtvedt** [comment]
This looks good to me. I will merge with the next release

**Pull request closed without merging**
